# Generated by Django 3.0.4 on 2020-06-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
