# Generated by Django 3.0.4 on 2020-06-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0002_producto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.IntegerField(),
        ),
    ]
