# Generated by Django 3.0.4 on 2020-06-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0003_auto_20200602_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('precio', models.FloatField(default=0.0)),
                ('producto', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.CharField(max_length=100),
        ),
    ]
